language: java
jdk: oraclejdk8

jobs:
  include:
    - stage: Build and test
      script: ./gradlew build
    - stage: Publish to gradle portal
      script: ./gradlew -PreleaseVersion=$TRAVIS_TAG :publishPlugins
      if: tag IS present
